sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
install:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.8/libsodium-1.0.8.tar.gz
  - tar xf libsodium-1.0.8.tar.gz
  - cd libsodium-1.0.8 && ./configure --prefix=$HOME/installed_libsodium && make && make install && cd ..
  - export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
  - export PATH=$HOME/.cargo/bin/:$PATH

script:
  - cargo test --all --verbose
