[package]
edition = "2018"
authors = ["Guanhao Yin <sopium@mysterious.site>"]
license = "Unlicense"
name = "noise-rust-crypto"
readme = "README.md"
repository = "https://github.com/sopium/noise-rust"
version = "0.2.0-dev"
description = "Wrappers of dalek and RustCrypto crates for noise-protocol"

[dependencies]
x25519-dalek = "0.5.2"
chacha20poly1305 = "0.2.0"
aes-gcm = "0.1.0"
blake2 = "0.8.1"
sha2 = "0.8.0"
rand_os = "0.1.3"
aead = "0.1.1"

[dependencies.noise-protocol]
path = "../noise-protocol"
version = "0.1.2-dev"

[dev-dependencies]
hex = "0.4"
